#!/bin/bash
set -eux -o pipefail

if (($# != 1)) || [[ ! -d $1 ]]; then
 echo "expected valid output directory as single argument"
 exit 1
fi
OUT=$(realpath -s $1)
# 80mb of 512b blocks
SECTORS=163840
BLOCKSIZE=512
PARTITION_OFFSET=63

dd if=/dev/zero of=${OUT}/temp.img count=${SECTORS} bs=${BLOCKSIZE}

# make partition table
# -a=dos to start partition at sector 63 instead of 2048
# todo: find a non-interactive version of this
fdisk -a dos -e ${OUT}/temp.img
# cut out mbr, rest is fs
dd if=${OUT}/temp.img of=${OUT}/fs.img bs=${BLOCKSIZE} skip=${PARTITION_OFFSET}
rm ${OUT}/temp.img

# create fat32 on fs.img
DEVICE=$(echo $(hdiutil attach -nomount ${OUT}/fs.img) | xargs)
set +x
read -p "create beansfs on ${DEVICE} (y/n)? " choice
case "${choice}" in
  y|Y ) echo "here goes :'-)";;
  n|N ) echo "aw :-("; exit 1;;
  * ) echo "sorry?"; exit 1;;
esac
set -x
# todo: read somewhere that -F doesn't work
newfs_msdos -F 32 ${DEVICE}
mkdir ${OUT}/mnt
mount -t msdos ${DEVICE} ${OUT}/mnt
ls ${OUT}/mnt
umount ${DEVICE}
hdiutil detach ${DEVICE}

# create boot sector
dd if=${OUT}/mbr of=${OUT}/boot.img bs=${BLOCKSIZE} count=1
# todo: move bootloader into fs and remove this
# bootloader lives right after mbr
dd if=${OUT}/boot bs=${BLOCKSIZE} count=1 >> ${OUT}/boot.img
# fill to 1mb
BOOTEND=$(($(stat -f %z ${OUT}/boot.img)))
BOOTPAD=$(((${PARTITION_OFFSET}*${BLOCKSIZE})-${BOOTEND}))
dd if=/dev/zero bs=1 count=${BOOTPAD} >> ${OUT}/boot.img

# create final disk
cat ${OUT}/boot.img ${OUT}/fs.img > ${OUT}/beans.img
file ${OUT}/beans.img
